In [1]:
import pygame,sys
import numpy as np
pygame.init()

pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html


(7, 0)

In [2]:
width=600
height=600
LineColor=(23,145,135)
line_width=15
circle_radius=60
circle_width=15
cross_width=25
space=55
circle_color=(239,231,200)
Blue=(28,170,156) #rgb formt-red/green/blue
cross_color=(66,66,66)

screen=pygame.display.set_mode((width,height))

In [3]:
pygame.display.set_caption("TIC TAC TOE")
screen.fill(Blue)

<rect(0, 0, 600, 600)>

In [4]:
#pygame.draw.line(screen, LineColor, (10,10),(300,300),10)

In [5]:
def draw_lines():
    pygame.draw.line(screen,LineColor,(0,200),(600,200),line_width)
    pygame.draw.line(screen,LineColor,(0,400),(600,400),line_width)
    #vertical
    pygame.draw.line(screen,LineColor,(200,0),(200,600),line_width)
    pygame.draw.line(screen,LineColor,(400,0),(400,600),line_width)
draw_lines()

In [6]:
board_rows=3
board_cols=3
board=np.zeros((board_rows,board_cols))
print(board)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
def mark_square(row,col,player):
    board[row][col]=player

In [8]:
def available_square(row,col):
    return board[row][col]==0

In [9]:
#mark_square(0,0,1)
#mark_square(1,1,2)
#print(available_square(1,1))
#print(board)

In [10]:
def board_is_full():
    for row in range(board_rows):
        for col in range(board_cols):
            if board[row][col]==0:
                return False
    return True

print(board_is_full())

False


In [11]:
'''for row in range(board_rows):
    for col in range(board_cols):
        mark_square(row,col,1)
print(board_is_full())'''

'for row in range(board_rows):\n    for col in range(board_cols):\n        mark_square(row,col,1)\nprint(board_is_full())'

In [12]:
player=1
game_over=False

In [13]:
def draw_figures():
    for row in range(board_rows):
        for col in range(board_cols):
            if board[row][col]==1:
                pygame.draw.circle(screen,circle_color,(int(col*200 + 100), int(row*200 + 100)),circle_radius,circle_width)
            elif board[row][col]==2:
                pygame.draw.line(screen,cross_color,(col*200+space,row*200+200-space),(col*200+200-space,row*200+space),cross_width)
                pygame.draw.line(screen,cross_color,(col*200+space,row*200+space),(col*200+200-space,row*200+200-space),cross_width)
                
                

In [14]:
def check_win(player):
    #vertical
    for col in range(board_cols):
        if board[0][col]==player and board[1][col]==player and board[2][col]==player:
            vertical_winning_line(col,player)
            return True
    #horizontal
    for row in range(board_rows):
        if board[row][0]==player and board[row][1]==player and board[row][2]==player:
            horizontal_winning_line(row,player)
            return True
    #ascending diagonal
    if board[2][0]==player and board[1][1]==player and board[0][2]:
        asc_diagonal(player)
        return True
    #descending
    if board[0][0]==player and board[1][1]==player and board[2][2]==player:
        desc_diagonal(player)
        return True
    return False

In [15]:
def vertical_winning_line(col,player):
    posX=col*200+100
    if player==1:
        color=circle_color
    elif player==2:
        color=cross_color
    pygame.draw.line(screen, color,(posX,15),(posX, height-15),15)

In [16]:
def horizontal_winning_line(row,player):
    posY=row*200+100
    if player==1:
        color=circle_color
    elif player==2:
        color=cross_color
    pygame.draw.line(screen, color,(15,posY),(width-15,posY),15)

In [17]:
def asc_diagonal(player):
    if player==1:
        color=circle_color
    elif player==2:
        color=cross_color
    pygame.draw.line(screen,color,(15,height-15),(width-15,15),15)

In [18]:
def desc_diagonal(player):
    if player==1:
        color=circle_color
    elif player==2:
        color=cross_color
    pygame.draw.line(screen,color,(15,15),(width-15,height-15),15)

In [19]:
def restart():
    screen.fill(Blue)
    draw_lines()
    player=1
    for row in range(board_rows):
        for col in range(board_cols):
            board[row][col]=0

In [ ]:
while True:
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            sys.exit()
        if event.type==pygame.MOUSEBUTTONDOWN and not game_over:
            mouseX=event.pos[0]#x
            mouseY=event.pos[1]#y
            print(mouseX)
            print(mouseY)

            clicked_row=int(mouseY//200)
            clicked_col=int(mouseX//200)
            
            if available_square(clicked_row,clicked_col):
                if player==1:
                    mark_square(clicked_row,clicked_col,1)
                    if check_win(player):
                        game_over=True
                    player=2
                elif player==2:
                    mark_square(clicked_row,clicked_col,2)
                    if check_win(player):
                        game_over=True
                    player=1
                draw_figures()
        if event.type==pygame.KEYDOWN:
            if event.key==pygame.K_y:
                restart()
                player=1
                game_over=False
    pygame.display.update()

299
112
294
274
458
36
499
529
127
79
